[package]
name = "bevy-space-invaders"
version = "0.1.0"
authors = ["Nicolas Hahn <nzh@fb.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.4"
